# -*- coding: utf-8 -*-

require "bundler/gem_tasks"
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
Bundler.setup
Bundler.require
require 'bubble-wrap/http'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'motion_resource_test_suite'
  app.identifier = 'com.n-so.motion-resource.test-suite'
  app.files += Dir.glob('./lib/motion-resource/**/*.rb')
  app.files = (app.files + Dir.glob('./app/**/*.rb')).uniq  
end
